# .goreleaser.yaml
project_name: bugscannerX

release:
  github:
    owner: tshackerz71
    name: bugscanner-go
  draft: false
  prerelease: false

builds:
  - id: bugscannerX
    main: ./cmd/main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w -X main.version={{.Version}}"

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

changelog:
  use: git

snapshot:
  name_template: "dev-{{ .Commit }}"
